### ISSUE TITLE
Support selecting between versions in the docs

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/hopr-docs#1]
The new documentation is based on Docusaurus. Since hoprd has many releases we want to be able to present the different versions of the documentation through the same page. A user should be able to select which version is presented through a drop-down field or an alternative mechanism.

# User Requirements

- be able to access `master` branch documentation
- be able to access `release/*` branch documentation for each release

**Comment by ayushkumar63123** [comment]
I can see only the master branch. Please create new branches for new releases.

**Comment by ayushkumar63123** [comment]
Use the “git flow release start” command to create the release branch. When the release is stable, run the “git flow release finish” command. $ git flow release finish '0.1. 0' Already on 'master' Deleted branch release/0.1.
The above suggestion is copied from google

**Comment by ayushkumar63123** [comment]
The dropdown will appear automatically once you publish a new release.

**Comment by ayushkumar63123** [comment]
Try, then ask if there are any questions.

**Comment by ayushkumar63123** [comment]
I have created an example for doing this. Take a look at my repository by going to link https://github.com/ayushkumar63123/GitcoinBountyDocusaurus
I have attached some screenshots of the example.
![Screenshot (341)](https://user-images.githubusercontent.com/86553805/142766450-ee182e49-3c4a-4357-93a6-6fe5849dc95b.png)
![Screenshot (342)](https://user-images.githubusercontent.com/86553805/142766452-91a21c5d-86ad-4d9a-95f2-465e2a141040.png)
![Screenshot (343)](https://user-images.githubusercontent.com/86553805/142766453-cda67947-323a-4499-ab4d-b484019a8884.png)

**Comment by ayushkumar63123** [comment]
I have created two releases (samples) tagged 1.01 and 1.02 that we can choose from the releases page.

**Comment by ayushkumar63123** [comment]
Is there anything else to do sir?

**Comment by tolbrino** [comment]
This issue isn't about creating tags/releases/branches in a Github repository. Its about seeing such branches as a drop-down in the documentation site generated by Docusaurus. Its clear that anybody can view the source of documentation on Github for the specific branches using Github's interface, but we need that capability for the generated and hosrted Docusaurus pages.

I checked your example repository and cannot find that functionality.

**Comment by ayushkumar63123** [comment]
I understand now. Let me work on that issue. I will inform you as soon as
it is resolved.

**Comment by ayushkumar63123** [comment]
My idea:- I am making in 10 minutes an html file that displays a dropdown menu for releases. Then commit that into the project repository. The user opens it and views the dropdown menu.

**Comment by tolbrino** [comment]
Take into account the page should be integrated into the Docusaurus setup and be generated. Release branch change all the time and we don't want to manage an html file manually.

**Comment by ayushkumar63123** [comment]
I have added the Releases.html file to release 1.03. Please check it and tell if its fine or I have to do more changes.

**Comment by ayushkumar63123** [comment]
Have you checked the file?

**Comment by ayushkumar63123** [comment]
hello, please check the file

**Comment by tolbrino** [comment]
Please read my messages carefully. We need a fully working Docusaurus setup, not a single hard-coded html file. Please provide a complete PR and don't expect feedback on each step of the way.

**Comment by ayushkumar63123** [comment]
For my information, I want to know what exactly is docusaurus. Is it some documentation and version management system for your github project?

**Comment by nionis** [comment]
hey @ayushkumar63123, this task has not been assigned to you, please check [the bounty](https://gitcoin.co/issue/hoprnet/hopr-docs/3/100027154). Somebody else was assigned to work on this 2 days ago. You will not receive any of the bounty price unless the bounty is assigned to you.

**Comment by ayushkumar63123** [comment]
Ok, sorry for disturbance caused. I misunderstood that this was a public
bounty. Is there any there bounty that is open and is not yet assigned?

**Comment by nionis** [comment]
No worries @ayushkumar63123, active issues are posted under https://gitcoin.co/hoprnet

**Comment by ayushkumar63123** [comment]
The man meant to do this was being late, so I gave the issue a last try.

**Comment by KedziaPawel** [comment]
Hello,
I've created PR to solve the issue https://github.com/hoprnet/hopr-docs/pull/5.
I would appreciate feedback and open discussion. I can adjust the solution to your needs if you have other preferences.
Cheers:)
