### ISSUE TITLE
RUST API version is outdated

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-docs#110]
We need to update docs with the latest RUST API v3. 

Current v2 specs file is located here: https://github.com/hoprnet/hopr-docs/blob/master/rest-api-v2-full-spec.json

With HOPRd version 2.1.0 it is capable to generate specs file automatically. Please find a way how docs could get the latest specs file.

**Comment by mjadach-iv** [comment]
I fixed it in 2.1 PR
