### ISSUE TITLE
Improve "Restore an Old Node" - missing `/`

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-docs#129]
The path is missing`/` at the end. `/app/hoprd-db/` is expected
![telegram-cloud-photo-size-1-5035098227229175203-y](https://github.com/user-attachments/assets/8af39572-7608-432b-b69b-4f7191d785a2)

**Comment by Jaguaras** [comment]
Fixed: https://github.com/hoprnet/hopr-docs/pull/131
