### ISSUE TITLE
Apply for DocSearch API key

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-docs#8]
@KedziaPawel It seems like we need to deploy the page first before applying for the API key.
> Your website must be production ready. We won't index empty websites nor those filled with placeholder content. Please, wait until you have written some documentation before applying. We would be happy to help you as soon as you have a steady design.

_Originally posted by @QYuQianchen in https://github.com/hoprnet/hopr-docs/issues/6#issuecomment-992333085_

**Comment by tolbrino** [comment]
Applied, waiting for key.
